# Generated by Django 2.2.7 on 2020-09-16 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vegetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vegetable_type', models.CharField(max_length=50)),
                ('vegetable_name', models.CharField(max_length=200)),
                ('season', models.CharField(max_length=50)),
            ],
        ),
    ]
